services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: devnest-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SERVERPASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - devnest_sql_data:/var/opt/mssql

  api:
    restart: unless-stopped
    build:
      context: ./backend/DevNest
      dockerfile: Dockerfile
    container_name: devnest-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}

      # IMPORTANT: use service name "db", NOT localhost
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}

      Jwt__Key: ${Jwt__Key}
      Jwt__Issuer: ${Jwt__Issuer}
      Jwt__Audience: ${Jwt__Audience}
      Brevo__ApiKey: ${Brevo__ApiKey}
      Brevo__SenderEmail: ${Brevo__SenderEmail}
      Brevo__SenderName: ${Brevo__SenderName}
      Frontend__BaseUrl: ${Frontend__BaseUrl}

      Cors__Origins__0: ${Cors__Origins__0}
    ports:
      - "5099:8080"

  frontend:
    build:
      context: ./frontend/devnestui
      dockerfile: Dockerfile
    container_name: devnest-frontend
    depends_on:
      - api
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/devnestui:/devnestui
      - /devnestui/node_modules

volumes:
  devnest_sql_data:
