services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: devnest-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SERVERPASSWORD}
      MSSQL_MEMORY_LIMIT_MB: "2048"
    ports:
      - "1433:1433"
    volumes:
      - devnest_sql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q "SELECT 1" -b -o /dev/null || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s

  api:
    restart: unless-stopped
    build:
      context: ./backend/DevNest
      dockerfile: Dockerfile
    container_name: devnest-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS:-http://0.0.0.0:8080}

      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}

      Jwt__Key: ${Jwt__Key}
      Jwt__Issuer: ${Jwt__Issuer}
      Jwt__Audience: ${Jwt__Audience}

      Brevo__ApiKey: ${Brevo__ApiKey}
      Brevo__SenderEmail: ${Brevo__SenderEmail}
      Brevo__SenderName: ${Brevo__SenderName}

      Report__InboxEmail: ${Report__InboxEmail}
      Report__InboxName: ${Report__InboxName}

      Frontend__BaseUrl: ${Frontend__BaseUrl}
      Cors__Origins__0: ${Cors__Origins__0}
    ports:
      - "127.0.0.1:5099:8080"
    volumes:
      - ./backend/DevNest:/DevNest

  frontend:
    build:
      context: ./frontend/devnestui
      dockerfile: Dockerfile
    container_name: devnest-frontend
    depends_on:
      - api
    environment:
      # IMPORTANT: this value is used by browser JS, so it must be host-reachable
      VITE_API_URL: ${VITE_API_URL:-http://localhost:5099/api}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/devnestui:/devnestui
      - /devnestui/node_modules

volumes:
  devnest_sql_data:
