services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: devnest-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - devnest_sql_data:/var/opt/mssql

  api:
    build:
      context: ./backend/DevNest
      dockerfile: Dockerfile
    container_name: devnest-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:8080

      # IMPORTANT: use service name "db", NOT localhost
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=DevNestDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False;"

      Jwt__Key: "gsn42g89nUNDUSNG-9iu83h&^48U$*u84u94indsugnDIHGUDSHfdsgDGSEvnvmGDJUSN$UN8u"
      Jwt__Issuer: "DevNest"
      Jwt__Audience: "DevNest"

      Cors__Origins__0: "http://localhost:5173"
    ports:
      - "5099:8080"

  frontend:
    build:
      context: ./frontend/devnestui
      dockerfile: Dockerfile
    container_name: devnest-frontend
    depends_on:
      - api
    environment:
      VITE_API_URL: "http://localhost:5099"
    ports:
      - "5173:5173"

volumes:
  devnest_sql_data:
